[build]
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  VITE_API_BASE_URL = "https://vr-mideros-backend.onrender.com"
  NODE_ENV = "production"
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefix=/opt/buildhome/.npm-global"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  [context.production.environment]
    VITE_API_BASE_URL = "https://vr-mideros-backend.onrender.com"

[context.deploy-preview]
  [context.deploy-preview.environment]
    VITE_API_BASE_URL = "https://vr-mideros-backend.onrender.com"